handlebars:
  suffix: .html

server:
  tomcat:
    accept-count: 8
    max-connections: 2
    threads:
      min-spare: 2
      max: 2
  compression:
    enabled: true
    mime-types: text/html,application/json,text/xml,text/css,text/plain
    min-response-size: 10
