handlebars:
  suffix: .html

server:
  tomcat:
    accept-count: 0
    max-connections: 2
    threads:
      max: 10
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json
    min-response-size: 0

spring:
  resources:
    static:
      cache:
        cachecontrol:
          max-age: 365d
          public: true
