handlebars:
  suffix: .html

server:
  tomcat:
    accept-count: 1 # 스레드별 작업 대기열 큐 대기 갯수
    max-connections: 2 # 최대로 처리 가능한 요청 수
    threads:
      min-spare: 1 # default 풀 사이즈
      max: 2  # 생성할 수 있는 최대 스레드 개수

  compression:
    enabled: true
    min-response-size: 10
