handlebars:
  suffix: .html

server:
  tomcat:
    accept-count: 10
    max-connections: 2
    threads:
      min-spare: 2
      max: 10
  compression:
    enabled: true
    min-response-size: 2
    mime-types: [text/html,text/xml,text/plain,text/css,application/javascript,application/json]
